---
- name: Converge
  hosts: all
  vars:
    - apache_build_version: '2.4.54'
    - apache_build_unarchive_remote_src: yes
  tasks:
    - name: "Include apache_build"
      include_role:
        name: "apache_build"
